services:
  - type: web
    name: my-steam-site
    runtime: python
    repo: https://github.com/Sasha98118/steam-auth-site.git
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: STEAM_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DOMAIN
        value: my-steam-site.onrender.com
      - key: USE_HTTPS
        value: "True"