services:
  - type: web
    name: steam-auth-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: STEAM_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DOMAIN
        value: steam-auth-site.onrender.com
      - key: USE_HTTPS
        value: "True"
      - key: CS2_SERVER_IP
        sync: false
      - key: CS2_SERVER_PORT
        value: "7638"
      - key: CS2_SERVER_PASSWORD
        sync: false
      - key: CS2_SERVER_NAME
        value: "PCS Cyber CS2 Server"
      - key: PTERO_API_URL
        sync: false
      - key: PTERO_API_KEY
        sync: false
      - key: PTERO_SERVER_ID
        sync: false